Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MIssion09_ahyer107.Models;

namespace MIssion09_ahyer107.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket cart;
        public CartSummaryViewComponent(Basket cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MIssion09_ahyer107.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MIssion09_ahyer107.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCat = RouteData?.Values["category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4 class="lead fw-bold"> <!--TA: The lead tag makes these words slightly taller and then the bold tage makes them dark to stand out-->
            @Model.Title
            <span class="badge bg-info" style="float:right">
                <small class="text-decoration-line-through">@((Model.Price*1.2).ToString("c"))</small> <!--TA: I used the line through modification here to make it look like like every book is on sale-->
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">Author: @Model.Author</div>
    <div class="card-text p-1">Publisher: @Model.Publisher</div>
    <div class="card-text p-1">Classification: @Model.Classification</div>
    <div class="card-text p-1">Category: @Model.Category</div>
    <div class="card-text p-1">PageCount: @Model.PageCount</div>

    <form method="post" asp-page="/Cart">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to cart</button>
        </span>
    </form>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Amazon</title>
    <link rel="stylesheet"
          asp-href-include="~/lib/css/bootstrap.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />"
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body class="bg-light">
    <!--TA: Here is where I added the light background tag-->
    @*<div class="bg-dark text-white p-2">
            <span class="navbar-brand ml-2">Welcome to Amazon</span>
        </div>*@

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">AMAZON</div>
                <div class="col-6 text-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">

        <div id="categories" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>

    </div>
    <script src="~/lib/js/bootstrap.js"></script>
</body>
</html>